#!/bin/sh

export D8_PATH=$HOME/src/node/deps/v8/out/native

case `uname -s` in
  Darwin )
    alias v8-tick-processor='$HOME/src/io.js/deps/v8/tools/mac-tick-processor'
    PATH=/usr/local/Cellar/openssl/1.0.1e/bin:/usr/local/bin:$PATH
    alias mongod="mongod --config /usr/local/etc/mongod.conf"
    ;;

  Linux )
    alias v8-tick-processor='$HOME/src/io.js/deps/v8/tools/linux-tick-processor'
    ;;
esac

export CLICOLOR=1
export EDITOR=vim
export NODE_REPL_HISTORY_FILE=$HOME/.node_history

# enable color support of ls and also add handy aliases
# Note that `ls` on MacOS does not support `--color` option
# and uses CLICOLOR instead
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

alias node-dev='$HOME/src/node/out/Release/node'
alias npm-dev='$HOME/src/npm/bin/npm-cli.js'
alias slc-dev='$HOME/src/strong/cli/bin/slc'
alias sl-npm='$HOME/src/sl-npm/bin/npm-cli.js'
alias npmjs='npm --userconfig ~/.strong-registry/default.ini'
alias slt-release='/usr/local/bin/slt-release -u'
alias makepwd='dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 | sed -e "s/=*$//"'
alias git-cleanup='git fetch -p && git branch --merged | grep -v "\*" | grep -v "^master\$" | xargs -n 1 git branch -d'
alias g=git
alias it=git
alias im=vim
alias mailcat='python -m smtpd -n -c DebuggingServer localhost:2525'
alias did="vim +'normal Go' +'r!date' ~/did.txt"

# Local host-specific configuration
[[ -f ~/.sh_local ]] && . ~/.sh_local

# vim:textwidth=0
