#!/bin/sh

export D8_PATH=$HOME/src/node/deps/v8/out/native

case `uname -s` in
  Darwin )
    alias v8-tick-processor='$HOME/src/node/deps/v8/tools/mac-tick-processor'
    PATH=/usr/local/Cellar/openssl/1.0.1e/bin:/usr/local/bin:$PATH
    ;;

  Linux )
    alias v8-tick-processor='$HOME/src/node/deps/v8/tools/linux-tick-processor'
    ;;
esac

export EDITOR=vim

PATH=$HOME/bin:$PATH
export PATH

alias node-dev='$HOME/src/node/out/Release/node'
alias npm-dev='$HOME/src/npm/bin/npm-cli.js'
alias slc-dev='$HOME/src/strong/cli/bin/slc'
alias sl-npm='$HOME/src/sl-npm/bin/npm-cli.js'
alias npmjs='npm --userconfig ~/.strong-registry/default.ini'
alias slt-release='npm_config_userconfig=$HOME/.strong-registry/default.ini /usr/local/bin/slt-release'
alias makepwd='dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 | sed -e "s/=*$//"'

# This loads NVM
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion
